### PR TITLE
add bed_maker manifest

### PR DESCRIPTION
**Pull request by joseverdezoto**

### CODE REVIEW

**Review by stolarczyk — CHANGES_REQUESTED** [review]
Can you use `docker_args` instead of `dockerargs`? Both work now, but the latter will probably become deprecated

**Review by stolarczyk — CHANGES_REQUESTED** [review]
another minor thing: maybe change the file name to `bed_maker.yaml` to match other manifests here?

**Review by stolarczyk — APPROVED** [review]
great, thanks!

**Comment by joseverdezoto** [comment]
I believe I merged the commits to the master branch. I guess I had admin rights to do it?

**Comment by stolarczyk** [comment]
yeah, every member of "shefflab" team has "Admin" permissions level

**Comment by nsheff** [comment]
looks great, thanks!

**Pull request merged**
